import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||process.cwd()+'/artifacts/browser/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process']});
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://test.shinetime.local/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="app"></div><div id="modal-root"></div><div id="toast-root"></div></body></html>'}));
 await page.goto('https://test.shinetime.local/');
 await page.addStyleTag({content:await readFile('assets/styles.css','utf8')});
 await page.addStyleTag({content:await readFile('assets/ui-system.css','utf8')});
 await page.addStyleTag({content:await readFile('assets/mobile-ui.css','utf8')});
 await page.addScriptTag({content:await readFile('assets/i18n.js','utf8')});
 await page.addScriptTag({content:await readFile('assets/operations-ui-core.js','utf8')});
 await page.addScriptTag({content:await readFile('assets/live-updates.js','utf8')});
 await page.evaluate(()=>{
   window.ST_BUILD='test';window.ST_BASE='/';window.testCalls=[];
   window.ShineTimeSupabase={subscribeJobs(cb){window.liveEvent=cb;return ()=>{}},request:async(path)=>{
    window.testCalls.push(path);
    if(path==='/api/cleaner/jobs/1')return {id:1,status:'CLEANING',object_code:'TEST-1',object_name:'Test apartment',payout:20,bonus:0,deadline:'20:00',checklist:[{id:1,label:'Proof',required:true,completed:true,photo_required:true,photo_category:"Owner's photo"}],photos:[{id:1,mime:'video/mp4',category:'Additional',url:'https://test.shinetime.local/video.mp4'}],issues:[]};
    if(path==='/api/client/profile')return {client:{full_name:'Test Owner',email:'owner@test.invalid',company_name:'Test Portfolio'}};
    if(path==='/api/client/dashboard')return {objects:{total:2,approved:2,pending:0},upcoming:[],completedToday:0,nextBooking:null};
    if(path==='/api/client/objects')return {objects:[]};
    if(path.startsWith('/api/cleaner/dashboard'))return {availability:{online:true,fromTime:'08:00',toTime:'20:00'},jobs:[],nextJob:null,total:0,earnings:0,projectedFinish:null};
    if(path==='/api/notifications')return {notifications:[],unread:0};
    if(path==='/api/admin/recurring')return {schedules:[]};
    if(path.includes('/settlements'))return {summary:{chargedCents:12345},jobs:[],hasMore:false};
    if(path.startsWith('/api/admin/jobs'))return {jobs:[{id:101,object_code:'BA-001',object_name:'Old Town apartment',address:'Dunajská 15, Bratislava',zone:'Bratislava — Staré Mesto',status:'UNASSIGNED',risk_level:'ORANGE',risk_score:68,planned_start:'10:00',eta:'11:30',payout:24,bonus:0},{id:102,object_code:'PR-001',object_name:'New Town apartment',address:'Vodičkova 20, Praha',zone:'Praha — Nové Město',status:'ACCEPTED',risk_level:'GREEN',risk_score:12,planned_start:'12:00',eta:'13:30',payout:28,bonus:0,cleaner_name:'Demo cleaner'}]};
    throw Error('Unexpected test route '+path);
   }};
 });
 await page.addScriptTag({content:await readFile(process.env.BASELINE_APP||'assets/app.js','utf8')});
 await page.addScriptTag({content:await readFile('assets/money.js','utf8')});
 await page.addScriptTag({content:await readFile('assets/operations-extension.js','utf8')});
 await page.evaluate(async()=>{state.me={id:1,role:'OWNER',full_name:'Test Owner',language:'en'};state.settings={};ST_I18N.setLocale('en');location.hash='client/profile';await render();startLiveUpdates();});
 await page.locator('[name=fullName]').fill('Unsaved portfolio owner');
 await page.evaluate(()=>window.liveEvent({table:'st_jobs'}));
 await page.waitForTimeout(700);
 assert.equal(await page.locator('[name=fullName]').inputValue(),'Unsaved portfolio owner','live event must retain unsaved input');
 assert.equal(await page.locator('[name=fullName]').evaluate(el=>el===document.activeElement),true,'focused field preserved');
 console.log('PASS: form value and focus survive realtime event');
 await page.evaluate(async()=>{state.me={id:2,role:'CLEANER',full_name:'Test Cleaner',language:'en'};location.hash='cleaner/home';await render();});
 await page.waitForTimeout(150);
 assert.equal(await page.locator('.bottom-nav').getByText('Map',{exact:true}).count(),0,'cleaner has no standalone map tab');
 assert.equal(await page.locator('#online-toggle').innerText(),'● ONLINE');
 assert.equal(await page.locator('.mobile-kpi').last().locator('.v').innerText(),'—','unknown projected finish is explicit');
 console.log('PASS: mobile cleaner home and availability');
 await page.evaluate(async()=>{window.ShineTimeSupabase.uploadProofFile=async(id,category,file)=>{window.lastUpload={id,category,mime:file.type};return {}};location.hash='cleaner/job/1';await render()});
 assert.equal(await page.locator('#page video').count(),1,'video report has a playable element');
 assert.equal(await page.getByRole('button',{name:'Complete cleaning',exact:true}).isDisabled(),true,'video does not satisfy required photo');
 await page.locator('input[type=file]').first().setInputFiles({name:'proof.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
 await page.waitForFunction(()=>window.lastUpload);
 assert.equal((await page.evaluate(()=>window.lastUpload)).category,"Owner's photo",'quoted category survives the upload event');
 await page.evaluate(async()=>{location.hash='cleaner/home';await render()});
 assert.equal(await page.locator('.cleaner-top').isVisible(),true,'header restored after leaving a job');
 console.log('PASS: photo upload UI, quoted categories, video proof and return navigation');

 await mkdir('artifacts',{recursive:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/cleaner-preview.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'no mobile horizontal overflow');
 await page.evaluate(async()=>{state.me={id:1,role:'OWNER',full_name:'Test Owner',company_name:'Test Portfolio',language:'en'};location.hash='client/home';await render()});
 await page.screenshot({path:'artifacts/owner-mobile-preview.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'owner page fits mobile viewport');
 await page.evaluate(async()=>{state.me={id:1,role:'ADMIN',full_name:'Operations',language:'en'};location.hash='admin/jobs';await render();});
 await page.locator('.mobile-menu-trigger').click();
 assert.equal(await page.locator('.mobile-menu-trigger').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('.sidebar').isVisible(),true);
 await page.getByRole('button',{name:'Close menu'}).click();
 assert.equal(await page.locator('.mobile-menu-trigger').getAttribute('aria-expanded'),'false');
 assert.equal(await page.locator('.admin-mobile-job').count(),2);
 await page.locator('#job-search').fill('Praha');
 assert.equal(await page.locator('.admin-mobile-job:visible').count(),1);
 assert.match(await page.locator('.admin-mobile-job:visible').innerText(),/PR-001/);
 await page.locator('#job-search').fill('');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'admin page fits mobile viewport');
 await page.setViewportSize({width:320,height:700});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'admin page fits a 320px viewport');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/admin-mobile-preview.png',fullPage:true});
 await page.evaluate(async()=>{state.me={id:3,role:'OPERATIONS_MANAGER',full_name:'Manager',language:'en'};location.hash='admin/jobs';await render()});
 assert.equal(await page.locator('.sidebar [data-route="admin/finance"]').count(),0,'manager drawer omits finance');
 assert.equal(await page.locator('.sidebar [data-route="admin/settings"]').count(),0,'manager drawer omits settings');
 console.log('PASS: mobile admin drawer, cards, search, role filtering and viewport');
 await page.evaluate(async()=>{state.me={id:1,role:'ADMIN',full_name:'Operations',language:'en'};location.hash='admin/jobs';await render()});
 await page.setViewportSize({width:1440,height:1000});
 await page.waitForTimeout(150);
 await page.screenshot({path:'artifacts/admin-preview.png',fullPage:true});
 await page.evaluate(async()=>{location.hash='admin/schedule';await render()});
 assert.match(await page.locator('#page').innerText(),/No recurring schedules yet/);
 await page.evaluate(async()=>{location.hash='admin/settlements';await render()});
 assert.match(await page.locator('#page').innerText(),/123[.,]45/);
 console.log('PASS: recurring schedules and exact settlement amounts render');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS: admin navigation and browser console');
}finally{await browser.close();}
