<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/lib/domain.php';

function api_json(mixed $data,int $status=200): never {
    http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
    echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);exit;
}
function api_body(): array {
    $raw=file_get_contents('php://input');
    if($raw===false||$raw==='')return [];
    if(strlen($raw)>8*1024*1024)throw new STHttpException('Payload too large',413);
    $d=json_decode($raw,true);if(!is_array($d))throw new STHttpException('Invalid JSON',400);return $d;
}
function api_date(): string { return isset($_GET['date'])&&preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$_GET['date'])?(string)$_GET['date']:st_today(); }
function api_in(string $key,array $body,mixed $default=null): mixed { return array_key_exists($key,$body)?$body[$key]:$default; }
function api_bool(mixed $v): int { return st_bool($v)?1:0; }
function api_photo_url(int $id): string { return st_base_path().'api/photos/'.$id; }

try {
    if(!st_is_installed())api_json(['error'=>'Application is not installed','install'=>st_base_path().'install.php'],503);
    st_start_session();
    $db=st_db();
    st_run_migrations($db);
    $route=trim((string)($_GET['route']??''),'/');
    $method=strtoupper($_SERVER['REQUEST_METHOD']??'GET');
    $user=st_current_user($db);

    if($route==='health'&&$method==='GET')api_json(['ok'=>true,'service'=>'Shine Time Operations','date'=>st_today(),'time'=>st_time()]);

    if($route==='login'&&$method==='POST'){
        $b=api_body();$found=st_authenticate($db,(string)($b['email']??''),(string)($b['password']??''));
        if(!$found)throw new STHttpException('Invalid email or password',401);
        session_regenerate_id(true);$_SESSION['user_id']=$found['id'];$_SESSION['csrf']=bin2hex(random_bytes(32));$resolved=st_current_user($db);
        api_json(['user'=>st_public_user($resolved),'csrf'=>$_SESSION['csrf']]);
    }

    if($method!=='GET')st_verify_csrf();

    if($route==='logout'&&$method==='POST'){
        $_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain']??'',(bool)$p['secure'],(bool)$p['httponly']);}session_destroy();api_json(['ok'=>true]);
    }
    if($route==='me'&&$method==='GET'){
        $me=st_require_user($user);api_json(['user'=>st_public_user($me),'settings'=>st_get_settings($db),'csrf'=>st_csrf_token()]);
    }
    if(preg_match('#^photos/(\d+)$#',$route,$m)&&$method==='GET'){
        $me=st_require_user($user);$s=$db->prepare('SELECT p.*,j.assigned_cleaner_id,j.client_id FROM job_photos p JOIN cleaning_jobs j ON j.id=p.job_id WHERE p.id=?');$s->execute([(int)$m[1]]);$p=$s->fetch();
        if(!$p)throw new STHttpException('Photo not found',404);if($me['role']==='CLEANER'&&(int)$me['cleaner_id']!==(int)$p['assigned_cleaner_id'])throw new STHttpException('Forbidden',403);if(in_array($me['role'],['OWNER','MANAGER'],true)&&(int)($me['client_id']??0)!==(int)($p['client_id']??0))throw new STHttpException('Forbidden',403);
        $full=dirname(__DIR__).'/storage/uploads/'.basename((string)$p['storage_path']);if(!is_file($full))throw new STHttpException('Photo file missing',404);
        header('Content-Type: '.($p['mime']?:'image/jpeg'));header('Content-Length: '.filesize($full));header('Cache-Control: private, no-store');readfile($full);exit;
    }
    if($route==='notifications'&&$method==='GET'){$me=st_require_user($user);$q=$db->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 50');$q->execute([$me['id']]);$rows=st_rows($q->fetchAll());$unread=count(array_filter($rows,fn($n)=>empty($n['read_at'])));api_json(['notifications'=>$rows,'unread'=>$unread]);}
    if($route==='notifications/read'&&$method==='POST'){$me=st_require_user($user);$db->prepare('UPDATE notifications SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE user_id=?')->execute([$me['id']]);api_json(['ok'=>true]);}
    if($route==='account/password'&&$method==='POST'){
        $me=st_require_user($user);$b=api_body();$current=(string)($b['currentPassword']??'');$new=(string)($b['newPassword']??'');
        if(!$current||!$new)throw new STHttpException('currentPassword and newPassword are required',400);if(strlen($new)<8)throw new STHttpException('New password must be at least 8 characters',400);
        $s=$db->prepare('SELECT password_hash FROM users WHERE id=?');$s->execute([$me['id']]);if(!password_verify($current,(string)$s->fetchColumn()))throw new STHttpException('Current password is incorrect',403);
        $s=$db->prepare('UPDATE users SET password_hash=? WHERE id=?');$s->execute([password_hash($new,PASSWORD_DEFAULT),$me['id']]);api_json(['ok'=>true]);
    }
    if($route==='account/language'&&$method==='PATCH'){
        $me=st_require_user($user);$b=api_body();$language=st_valid_locale((string)($b['language']??'ru'));$db->prepare('UPDATE users SET language=? WHERE id=?')->execute([$language,$me['id']]);api_json(['language'=>$language]);
    }

    // CLEANER
    if(str_starts_with($route,'cleaner/')){
        $me=st_require_user($user,'CLEANER');$cleanerId=(int)$me['cleaner_id'];$date=api_date();
        if($route==='cleaner/dashboard'&&$method==='GET'){
            $s=$db->prepare('SELECT * FROM cleaner_availability WHERE cleaner_id=? AND service_date=?');$s->execute([$cleanerId,$date]);$a=$s->fetch()?:['online'=>0,'from_time'=>'10:00','to_time'=>'15:00'];$a=st_normalize_row($a);
            $day=st_project_cleaner_day($db,$cleanerId,$date);$completed=array_values(array_filter($day['jobs'],fn($j)=>$j['status']==='COMPLETED'));$earnings=array_reduce($completed,fn($sum,$j)=>$sum+(float)$j['payout']+(float)$j['bonus'],0.0);$active=null;foreach($day['jobs'] as $j)if(!in_array($j['status'],['COMPLETED','CANCELLED'],true)){$active=$j;break;}
            api_json(['date'=>$date,'availability'=>['online'=>(bool)$a['online'],'fromTime'=>st_time5($a['from_time'])?:'10:00','toTime'=>st_time5($a['to_time'])?:'15:00'],'jobs'=>$day['jobs'],'nextJob'=>$active,'projectedFinish'=>$day['projectedFinish'],'earnings'=>$earnings,'completed'=>count($completed),'total'=>count($day['jobs'])]);
        }
        if($route==='cleaner/availability'&&$method==='PATCH'){
            $b=api_body();$serviceDate=(string)($b['date']??$date);$from=(string)($b['fromTime']??'10:00');$to=(string)($b['toTime']??'15:00');
            if(st_to_minutes($from)<st_to_minutes('10:00')||st_to_minutes($to)>st_to_minutes('15:00')||st_to_minutes($from)>=st_to_minutes($to))throw new STHttpException('Availability must be inside 10:00–15:00',400);
            $s=$db->prepare('INSERT INTO cleaner_availability(cleaner_id,service_date,online,from_time,to_time) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE online=VALUES(online),from_time=VALUES(from_time),to_time=VALUES(to_time)');$s->execute([$cleanerId,$serviceDate,api_bool($b['online']??false),$from,$to]);
            if(isset($b['lat'],$b['lng'])){$s=$db->prepare('UPDATE cleaners SET last_lat=?,last_lng=?,last_location_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([(float)$b['lat'],(float)$b['lng'],$cleanerId]);}
            api_json(['availability'=>['online'=>st_bool($b['online']??false),'fromTime'=>$from,'toTime'=>$to,'date'=>$serviceDate]]);
        }
        if($route==='cleaner/marketplace'&&$method==='GET'){
            $existing=array_values(array_filter(st_assigned_jobs($db,$cleanerId,$date),fn($j)=>$j['status']!=='COMPLETED'));$settings=st_cleaner_dispatch_settings($db,$cleanerId,$date);
            $s=$db->prepare(st_job_select()." WHERE j.service_date=? AND j.marketplace_visible=1 AND j.assigned_cleaner_id IS NULL AND j.status IN ('UNASSIGNED','OFFERED','AT_RISK','RESCUE') ORDER BY j.planned_start,j.id");$s->execute([$date]);$raw=st_rows($s->fetchAll());$jobs=[];
            $existingCore=array_map(fn($x)=>['id'=>$x['id'],'zone'=>$x['zone'],'durationMinutes'=>$x['duration_minutes'],'plannedStart'=>$x['planned_start']],$existing);
            foreach($raw as $j){$check=st_can_accept_job($existingCore,['id'=>$j['id'],'zone'=>$j['zone'],'durationMinutes'=>$j['duration_minutes'],'plannedStart'=>$j['planned_start'],'deadline'=>min((string)$j['deadline'],(string)$settings['windowEnd'])],$settings);$d=st_decorate_job_risk($j);$marketTime=$j['service_date']===st_today()?st_time():'10:00';$d['bonus']=st_effective_marketplace_bonus($j,$marketTime);$d['feasible']=$check['ok'];$d['feasibility_reason']=$check['reason'];$d['projected_finish']=$check['projectedFinish'];foreach(['access_instructions','key_instructions','linen_location','supplies_location','wifi'] as $k)unset($d[$k]);$jobs[]=$d;}
            $bundleJobs=array_map(fn($j)=>['id'=>$j['id'],'zone'=>$j['zone'],'durationMinutes'=>$j['duration_minutes'],'plannedStart'=>$j['planned_start'],'payout'=>(float)$j['payout'],'bonus'=>(float)$j['bonus']],array_values(array_filter($jobs,fn($j)=>$j['feasible'])));
            api_json(['date'=>$date,'jobs'=>$jobs,'bundles'=>st_generate_smart_bundles($bundleJobs,$existingCore,$settings)]);
        }
        if($route==='cleaner/earnings'&&$method==='GET'){
            $s=$db->prepare(st_job_select()." WHERE j.assigned_cleaner_id=? AND j.status='COMPLETED' ORDER BY j.service_date DESC,j.completed_at DESC LIMIT 200");$s->execute([$cleanerId]);$rows=st_rows($s->fetchAll());$today=st_today();$todayTotal=0;$total=0;foreach($rows as $j){$v=(float)$j['payout']+(float)$j['bonus'];$total+=$v;if($j['service_date']===$today)$todayTotal+=$v;}api_json(['today'=>$todayTotal,'total'=>$total,'jobs'=>$rows]);
        }
        if($route==='cleaner/notifications'&&$method==='GET'){$s=$db->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 50');$s->execute([$me['id']]);api_json(['notifications'=>st_rows($s->fetchAll())]);}
        if(preg_match('#^cleaner/jobs/(\d+)$#',$route,$m)&&$method==='GET'){$j=st_get_job($db,(int)$m[1]);if(!$j)throw new STHttpException('Job not found',404);if((int)$j['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('This job is not assigned to you',403);api_json(st_full_job($db,(int)$m[1],true));}
        if(preg_match('#^cleaner/jobs/(\d+)/accept$#',$route,$m)&&$method==='POST'){
            $id=(int)$m[1];$job=st_get_job($db,$id);if(!$job)throw new STHttpException('Job not found',404);if($job['assigned_cleaner_id'])throw new STHttpException('Job is already assigned',409);if(!$job['marketplace_visible']||!in_array($job['status'],['UNASSIGNED','OFFERED','AT_RISK','RESCUE'],true))throw new STHttpException('Job is not available',409);
            $existing=array_values(array_filter(st_assigned_jobs($db,$cleanerId,$job['service_date']),fn($j)=>$j['status']!=='COMPLETED'));$dispatch=st_cleaner_dispatch_settings($db,$cleanerId,$job['service_date']);$core=array_map(fn($x)=>['id'=>$x['id'],'zone'=>$x['zone'],'durationMinutes'=>$x['duration_minutes'],'plannedStart'=>$x['planned_start']],$existing);$effectiveDeadline=min((string)$job['deadline'],(string)$dispatch['windowEnd']);$check=st_can_accept_job($core,['id'=>$job['id'],'zone'=>$job['zone'],'durationMinutes'=>$job['duration_minutes'],'plannedStart'=>$job['planned_start'],'deadline'=>$effectiveDeadline],$dispatch);if(!$check['ok'])throw new STHttpException($check['reason'],409,['projectedFinish'=>$check['projectedFinish']]);
            $marketTime=$job['service_date']===st_today()?st_time():'10:00';$bonus=st_effective_marketplace_bonus($job,$marketTime);$s=$db->prepare("UPDATE cleaning_jobs SET assigned_cleaner_id=?,status='ACCEPTED',accepted_at=?,bonus=?,marketplace_visible=0,rescue_state='NONE',updated_at=CURRENT_TIMESTAMP WHERE id=? AND assigned_cleaner_id IS NULL");$s->execute([$cleanerId,st_now(),$bonus,$id]);if($s->rowCount()!==1)throw new STHttpException('Job was taken by another cleaner',409);$a=$db->prepare('INSERT INTO cleaner_availability(cleaner_id,service_date,online,from_time,to_time) VALUES(?,?,1,?,?) ON DUPLICATE KEY UPDATE online=1');$a->execute([$cleanerId,$job['service_date'],$dispatch['windowStart'],$dispatch['windowEnd']]);$day=st_update_job_plan_for_cleaner($db,$cleanerId,$job['service_date']);st_add_event($db,$id,$me['id'],'JOB_ACCEPTED',['cleanerId'=>$cleanerId]);st_notify($db,$me['id'],'JOB_ACCEPTED','Job accepted',$job['object_code'].' added to My Day');api_json(['job'=>st_get_job($db,$id),'day'=>$day]);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/status$#',$route,$m)&&$method==='POST'){
            $id=(int)$m[1];$b=api_body();$job=st_get_job($db,$id);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);$status=(string)($b['status']??'');if(!in_array($status,['EN_ROUTE','ARRIVED','CLEANING'],true))throw new STHttpException('Invalid status',400);
            $sets=['status=?'];$args=[$status];$warning=null;$distance=null;if($status==='ARRIVED'){$sets[]='actual_checkin=?';$args[]=st_now();if(isset($b['lat'],$b['lng'])){$sets[]='checkin_lat=?';$sets[]='checkin_lng=?';$args[]=(float)$b['lat'];$args[]=(float)$b['lng'];$q=$db->prepare('UPDATE cleaners SET last_lat=?,last_lng=?,last_location_at=CURRENT_TIMESTAMP WHERE id=?');$q->execute([(float)$b['lat'],(float)$b['lng'],$cleanerId]);if($job['lat']!==null&&$job['lng']!==null){$distance=st_distance_meters((float)$job['lat'],(float)$job['lng'],(float)$b['lat'],(float)$b['lng']);$radius=(int)(st_get_settings($db)['checkinRadiusMeters']??250);if($distance>$radius)$warning='GPS check-in is '.round($distance).' m from the object (allowed radius '.$radius.' m). Operations can review this check-in.';}}}if($status==='CLEANING'){$sets[]='actual_start=?';$args[]=st_now();}$args[]=$id;$q=$db->prepare('UPDATE cleaning_jobs SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=?');$q->execute($args);st_add_event($db,$id,$me['id'],'STATUS_'.$status,['lat'=>$b['lat']??null,'lng'=>$b['lng']??null,'distanceMeters'=>$distance]);if($warning)st_add_event($db,$id,$me['id'],'CHECKIN_OUTSIDE_RADIUS',['distanceMeters'=>round($distance),'warning'=>$warning]);api_json(['job'=>st_get_job($db,$id),'warning'=>$warning]);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/checklist/(\d+)$#',$route,$m)&&$method==='PATCH'){
            $jobId=(int)$m[1];$itemId=(int)$m[2];$b=api_body();$job=st_get_job($db,$jobId);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);$q=$db->prepare('SELECT * FROM job_checklist WHERE id=? AND job_id=?');$q->execute([$itemId,$jobId]);if(!$q->fetch())throw new STHttpException('Checklist item not found',404);$done=st_bool($b['completed']??false);$q=$db->prepare('UPDATE job_checklist SET completed=?,completed_at=? WHERE id=?');$q->execute([$done?1:0,$done?st_now():null,$itemId]);st_add_event($db,$jobId,$me['id'],'CHECKLIST_UPDATED',['itemId'=>$itemId,'completed'=>$done]);$q=$db->prepare('SELECT * FROM job_checklist WHERE id=?');$q->execute([$itemId]);api_json(['item'=>st_normalize_row($q->fetch())]);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/photos$#',$route,$m)&&$method==='POST'){
            $jobId=(int)$m[1];$b=api_body();$job=st_get_job($db,$jobId);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);if(empty($b['category'])||empty($b['dataBase64']))throw new STHttpException('category and dataBase64 are required',400);
            $raw=(string)$b['dataBase64'];if(str_contains($raw,','))$raw=substr($raw,strpos($raw,',')+1);$bytes=base64_decode($raw,true);if($bytes===false)throw new STHttpException('Invalid photo data',400);if(strlen($bytes)>5*1024*1024)throw new STHttpException('Photo must be under 5 MB',413);$info=@getimagesizefromstring($bytes);if(!$info)throw new STHttpException('Uploaded file is not a valid image',400);$mime=$info['mime']??'image/jpeg';$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime]))throw new STHttpException('Only JPEG, PNG and WebP photos are supported',400);$stored=bin2hex(random_bytes(16)).'.'.$allowed[$mime];$path=dirname(__DIR__).'/storage/uploads/'.$stored;if(file_put_contents($path,$bytes,LOCK_EX)===false)throw new STHttpException('Unable to save photo',500);
            $q=$db->prepare('INSERT INTO job_photos(job_id,cleaner_id,checklist_item_id,category,file_name,mime,storage_path,file_size) VALUES(?,?,?,?,?,?,?,?)');$q->execute([$jobId,$cleanerId,$b['checklistItemId']??null,(string)$b['category'],basename((string)($b['fileName']??'photo.jpg')),$mime,$stored,strlen($bytes)]);$pid=(int)$db->lastInsertId();st_add_event($db,$jobId,$me['id'],'PHOTO_UPLOADED',['category'=>$b['category'],'photoId'=>$pid]);$q=$db->prepare('SELECT id,job_id,cleaner_id,checklist_item_id,category,file_name,mime,file_size,created_at FROM job_photos WHERE id=?');$q->execute([$pid]);$photo=st_normalize_row($q->fetch());$photo['url']=api_photo_url($pid);api_json(['photo'=>$photo],201);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/issues$#',$route,$m)&&$method==='POST'){
            $jobId=(int)$m[1];$b=api_body();$job=st_get_job($db,$jobId);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);$type=(string)($b['type']??'Other');$priority=in_array($type,['Guest still inside','Missing key','Damage'],true)?'HIGH':'NORMAL';$q=$db->prepare("INSERT INTO issues(job_id,cleaner_id,type,description,photos_json,status,priority) VALUES(?,?,?,?,?,'OPEN',?)");$q->execute([$jobId,$cleanerId,$type,(string)($b['description']??''),st_json($b['photos']??[]),$priority]);$iid=(int)$db->lastInsertId();$db->prepare('UPDATE cleaning_jobs SET issue_flag=1,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$jobId]);st_add_event($db,$jobId,$me['id'],'ISSUE_REPORTED',['issueId'=>$iid,'type'=>$type]);$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],'ISSUE','Issue: '.$type,$job['object_code'].' requires attention');$q=$db->prepare('SELECT * FROM issues WHERE id=?');$q->execute([$iid]);api_json(['issue'=>st_normalize_row($q->fetch())],201);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/complete$#',$route,$m)&&$method==='POST'){
            $jobId=(int)$m[1];$job=st_get_job($db,$jobId);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);$q=$db->prepare('SELECT COUNT(*) FROM job_checklist WHERE job_id=? AND required=1 AND completed=0');$q->execute([$jobId]);$missingChecklist=(int)$q->fetchColumn();$q=$db->prepare('SELECT DISTINCT photo_category FROM job_checklist WHERE job_id=? AND photo_required=1 AND photo_category IS NOT NULL');$q->execute([$jobId]);$requiredCats=array_column($q->fetchAll(),'photo_category');$q=$db->prepare('SELECT DISTINCT category FROM job_photos WHERE job_id=?');$q->execute([$jobId]);$present=array_column($q->fetchAll(),'category');$missingPhotos=array_values(array_diff($requiredCats,$present));if($missingChecklist||$missingPhotos)throw new STHttpException('Required cleaning proof is incomplete',409,['missingChecklist'=>$missingChecklist,'missingPhotos'=>$missingPhotos]);
            $completedAt=st_now();$q=$db->prepare("UPDATE cleaning_jobs SET status='COMPLETED',completed_at=?,eta=?,risk_score=0,risk_level='GREEN',risk_reasons='[]',rescue_state='NONE',updated_at=CURRENT_TIMESTAMP WHERE id=?");$q->execute([$completedAt,st_time(),$jobId]);$db->prepare('UPDATE cleaners SET completed_jobs=completed_jobs+1 WHERE id=?')->execute([$cleanerId]);st_add_event($db,$jobId,$me['id'],'JOB_COMPLETED',['completedAt'=>$completedAt]);st_notify($db,$me['id'],'COMPLETED','Cleaning completed',$job['object_code'].' marked ready');api_json(['job'=>st_get_job($db,$jobId)]);
        }
        if(preg_match('#^cleaner/jobs/(\d+)/cancel$#',$route,$m)&&$method==='POST'){
            $jobId=(int)$m[1];$b=api_body();$job=st_get_job($db,$jobId);if(!$job)throw new STHttpException('Job not found',404);if((int)$job['assigned_cleaner_id']!==$cleanerId)throw new STHttpException('Not your job',403);if($job['status']==='COMPLETED')throw new STHttpException('Completed job cannot be cancelled',409);$reason=trim((string)($b['reason']??''));if(!$reason)throw new STHttpException('Cancellation reason is required',400);$settings=st_get_settings($db);$cutoff=(int)($settings['cleanerCancellationCutoffMinutes']??90);$planned=st_to_minutes((string)($job['planned_start']?:$job['earliest_start']?:'10:00'));$late=$job['service_date']===st_today() && st_to_minutes(st_time()) >= $planned-$cutoff;$nextStatus=$late?'RESCUE':'UNASSIGNED';$rescue=$late?'ACTIVE':'NONE';$bonus=$late?max((float)$job['bonus'],6):(float)$job['bonus'];$q=$db->prepare("UPDATE cleaning_jobs SET assigned_cleaner_id=NULL,status=?,marketplace_visible=1,cancellation_reason=?,accepted_at=NULL,rescue_state=?,bonus=?,updated_at=CURRENT_TIMESTAMP WHERE id=?");$q->execute([$nextStatus,$reason,$rescue,$bonus,$jobId]);$penalty=$late?3:1;$cancelAdd=$late?1.5:0.5;$db->prepare('UPDATE cleaners SET cancellation_rate=LEAST(100,cancellation_rate+?),reliability_score=GREATEST(0,reliability_score-?) WHERE id=?')->execute([$cancelAdd,$penalty,$cleanerId]);st_add_event($db,$jobId,$me['id'],$late?'LATE_CLEANER_CANCELLED':'CLEANER_CANCELLED',['reason'=>$reason,'rescue'=>$late]);$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],$late?'RESCUE':'CANCELLED',$late?'Late cancellation — Rescue opened':'Cleaner cancelled job',$job['object_code'].' · '.$reason);api_json(['job'=>st_get_job($db,$jobId),'rescue'=>$late]);
        }
    }


    // OWNER / MANAGER CLIENT PORTAL
    if(str_starts_with($route,'client/')){
        $me=st_require_user($user,['OWNER','MANAGER']);$clientId=(int)($me['client_id']??0);if(!$clientId)throw new STHttpException('Client account is not configured',403);$date=api_date();
        if($route==='client/dashboard'&&$method==='GET'){
            $q=$db->prepare('SELECT COUNT(*) total,SUM(approval_status=\'APPROVED\' AND active=1) approved,SUM(approval_status=\'PENDING\') pending FROM objects WHERE client_id=?');$q->execute([$clientId]);$objects=st_normalize_row($q->fetch()?:['total'=>0,'approved'=>0,'pending'=>0]);
            $q=$db->prepare(st_job_select()." WHERE j.client_id=? AND j.service_date>=? AND j.status!='CANCELLED' ORDER BY j.service_date,COALESCE(j.planned_start,j.earliest_start),j.id LIMIT 20");$q->execute([$clientId,st_today()]);$upcoming=array_map('st_client_job_public',st_rows($q->fetchAll()));
            $next=$upcoming[0]??null;$q=$db->prepare("SELECT COUNT(*) FROM cleaning_jobs WHERE client_id=? AND service_date=? AND status='COMPLETED'");$q->execute([$clientId,st_today()]);$completedToday=(int)$q->fetchColumn();
            api_json(['date'=>st_today(),'objects'=>['total'=>(int)($objects['total']??0),'approved'=>(int)($objects['approved']??0),'pending'=>(int)($objects['pending']??0)],'upcoming'=>$upcoming,'nextBooking'=>$next,'completedToday'=>$completedToday]);
        }
        if($route==='client/objects'&&$method==='GET'){
            $q=$db->prepare('SELECT * FROM objects WHERE client_id=? ORDER BY approval_status,active DESC,code');$q->execute([$clientId]);api_json(['objects'=>st_rows($q->fetchAll())]);
        }
        if($route==='client/objects'&&$method==='POST'){
            $b=api_body();foreach(['name','address','zone'] as $k)if(empty($b[$k]))throw new STHttpException('name, address and zone are required',400);$code=trim((string)($b['code']??''));if(!$code)$code='CL'.$clientId.'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));
            try{$q=$db->prepare("INSERT INTO objects(client_id,code,name,address,zone,lat,lng,apartment_type,bedrooms,bathrooms,duration_minutes,payout,client_price,checkout_time,deadline_time,access_instructions,key_instructions,parking,linen_location,supplies_location,wifi,notes,active,approval_status) VALUES(?,?,?,?,?,?,?,?,?,?,60,0,0,'10:00','15:00',?,?,?,?,?,?,?,0,'PENDING')");$q->execute([$clientId,$code,$b['name'],$b['address'],$b['zone'],$b['lat']??null,$b['lng']??null,$b['apartmentType']??'Apartment',(int)($b['bedrooms']??1),(int)($b['bathrooms']??1),$b['accessInstructions']??'',$b['keyInstructions']??'',$b['parking']??'',$b['linenLocation']??'',$b['suppliesLocation']??'',$b['wifi']??'',$b['notes']??'']);}
            catch(PDOException $e){if(($e->errorInfo[1]??0)===1062)throw new STHttpException('Object code already exists',409);throw $e;}
            $id=(int)$db->lastInsertId();st_insert_default_checklist($db,$id);$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],'CLIENT_OBJECT','New object awaiting approval',$b['name'].' · '.$b['address']);$q=$db->prepare('SELECT * FROM objects WHERE id=?');$q->execute([$id]);api_json(['object'=>st_normalize_row($q->fetch())],201);
        }
        if(preg_match('#^client/objects/(\d+)$#',$route,$m)){
            $oid=(int)$m[1];$object=st_client_object($db,$clientId,$oid,false);if(!$object)throw new STHttpException('Object not found',404);
            if($method==='GET'){api_json(['object'=>$object]);}
            if($method==='PATCH'){$b=api_body();$map=['name'=>'name','address'=>'address','zone'=>'zone','lat'=>'lat','lng'=>'lng','apartmentType'=>'apartment_type','bedrooms'=>'bedrooms','bathrooms'=>'bathrooms','accessInstructions'=>'access_instructions','keyInstructions'=>'key_instructions','parking'=>'parking','linenLocation'=>'linen_location','suppliesLocation'=>'supplies_location','wifi'=>'wifi','notes'=>'notes'];$sets=[];$args=[];$requiresApproval=false;foreach($map as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$b[$k];if(in_array($k,['name','address','zone','lat','lng','apartmentType','bedrooms','bathrooms'],true))$requiresApproval=true;}if($requiresApproval){$sets[]="approval_status='PENDING'";$sets[]='active=0';}if($sets){$args[]=$oid;$db->prepare('UPDATE objects SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=? AND client_id=?')->execute([...$args,$clientId]);}if($requiresApproval){$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],'CLIENT_OBJECT','Object changes awaiting approval',$object['code'].' · '.$object['name']);}$q=$db->prepare('SELECT * FROM objects WHERE id=?');$q->execute([$oid]);api_json(['object'=>st_normalize_row($q->fetch())]);}
        }
        if($route==='client/slots'&&$method==='GET'){
            $oid=(int)($_GET['objectId']??0);$serviceDate=(string)($_GET['date']??'');if(!$oid||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$serviceDate))throw new STHttpException('objectId and valid date are required',400);if($serviceDate<st_today())throw new STHttpException('Cannot book a past date',400);$o=st_client_object($db,$clientId,$oid,true);if(!$o)throw new STHttpException('Object is not approved for booking',404);$slots=st_client_booking_slots($db,$clientId,$oid,$serviceDate);api_json(['date'=>$serviceDate,'object'=>$o,'slots'=>$slots,'capacity'=>st_client_booking_capacity($db,$serviceDate)]);
        }
        if($route==='client/bookings'&&$method==='GET'){
            $from=(string)($_GET['from']??(new DateTimeImmutable('-90 days'))->format('Y-m-d'));$to=(string)($_GET['to']??(new DateTimeImmutable('+365 days'))->format('Y-m-d'));$q=$db->prepare(st_job_select().' WHERE j.client_id=? AND j.service_date BETWEEN ? AND ? ORDER BY j.service_date DESC,COALESCE(j.planned_start,j.earliest_start),j.id DESC');$q->execute([$clientId,$from,$to]);api_json(['bookings'=>array_map('st_client_job_public',st_rows($q->fetchAll()))]);
        }
        if($route==='client/bookings'&&$method==='POST'){
            $b=api_body();$oid=(int)($b['objectId']??0);$serviceDate=(string)($b['serviceDate']??'');$start=(string)($b['startTime']??'');if(!$oid||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$serviceDate)||!preg_match('/^\d{2}:\d{2}$/',$start))throw new STHttpException('objectId, serviceDate and startTime are required',400);if($serviceDate<st_today())throw new STHttpException('Cannot book a past date',400);$o=st_client_object($db,$clientId,$oid,true);if(!$o)throw new STHttpException('Object is not approved for booking',404);$slots=st_client_booking_slots($db,$clientId,$oid,$serviceDate);if(!in_array($start,$slots,true))throw new STHttpException('This cleaning slot is no longer available',409,['availableSlots'=>$slots]);$job=st_create_job_from_object($db,$oid,$serviceDate,['clientId'=>$clientId,'plannedStart'=>$start,'earliestStart'=>$start,'deadline'=>$o['deadline_time']?:'15:00','bookingSource'=>'CLIENT_BOOKING','createdByUserId'=>$me['id'],'marketplaceVisible'=>true]);st_add_event($db,$job['id'],$me['id'],'CLIENT_BOOKED',['startTime'=>$start]);$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],'CLIENT_BOOKING','New client cleaning reservation',$o['code'].' · '.$serviceDate.' '.$start);api_json(['booking'=>st_client_job_public(st_get_job($db,$job['id'])??$job)],201);
        }
        if(preg_match('#^client/bookings/(\d+)$#',$route,$m)&&$method==='GET'){
            $jid=(int)$m[1];$job=st_get_job($db,$jid);if(!$job||(int)($job['client_id']??0)!==$clientId)throw new STHttpException('Booking not found',404);$detail=st_full_job($db,$jid,false);if(!$detail)throw new STHttpException('Booking not found',404);$photos=$detail['photos']??[];foreach($photos as &$p)$p['url']=api_photo_url((int)$p['id']);unset($p);api_json(['booking'=>st_client_job_public($detail),'checklist'=>$detail['checklist']??[],'photos'=>$photos,'issues'=>$detail['issues']??[]]);
        }
        if(preg_match('#^client/bookings/(\d+)/cancel$#',$route,$m)&&$method==='POST'){
            $jid=(int)$m[1];$b=api_body();$job=st_get_job($db,$jid);if(!$job||(int)($job['client_id']??0)!==$clientId)throw new STHttpException('Booking not found',404);if(in_array($job['status'],['COMPLETED','CANCELLED'],true))throw new STHttpException('This booking cannot be cancelled',409);$settings=st_get_settings($db);$cutoff=max(0,(int)($settings['clientCancellationCutoffHours']??12));$tz=new DateTimeZone('Europe/Bratislava');$planned=new DateTimeImmutable($job['service_date'].' '.($job['planned_start']?:$job['earliest_start']?:'10:00'),$tz);$deadline=$planned->modify('-'.$cutoff.' hours');if(new DateTimeImmutable('now',$tz)>$deadline)throw new STHttpException('Cancellation cutoff has passed. Contact Operations.',409);$reason=trim((string)($b['reason']??'Cancelled by client'));$assigned=(int)($job['assigned_cleaner_id']??0);$db->prepare("UPDATE cleaning_jobs SET status='CANCELLED',marketplace_visible=0,cancellation_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$reason,$jid]);if($assigned){$q=$db->prepare('SELECT user_id FROM cleaners WHERE id=?');$q->execute([$assigned]);$uid=(int)$q->fetchColumn();if($uid)st_notify($db,$uid,'CLIENT_CANCELLED','Cleaning cancelled',$job['object_code'].' · '.$job['service_date']);st_update_job_plan_for_cleaner($db,$assigned,$job['service_date']);}st_add_event($db,$jid,$me['id'],'CLIENT_CANCELLED',['reason'=>$reason]);$admins=$db->query("SELECT id FROM users WHERE role='ADMIN' AND active=1")->fetchAll();foreach($admins as $a)st_notify($db,(int)$a['id'],'CLIENT_CANCELLED','Client cancelled cleaning',$job['object_code'].' · '.$job['service_date']);api_json(['booking'=>st_client_job_public(st_get_job($db,$jid)??$job)]);
        }
        if($route==='client/profile'&&$method==='GET'){api_json(['client'=>st_client_account($db,$clientId),'user'=>st_public_user($me)]);}
        if($route==='client/profile'&&$method==='PATCH'){
            $b=api_body();$umap=['fullName'=>'full_name','phone'=>'phone','email'=>'email','language'=>'language'];$sets=[];$args=[];foreach($umap as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$k==='language'?st_valid_locale((string)$b[$k]):$b[$k];}if($sets){$args[]=$me['id'];$db->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=?')->execute($args);}$cmap=['companyName'=>'company_name','billingName'=>'billing_name','ico'=>'ico','dic'=>'dic','icDph'=>'ic_dph','billingAddress'=>'billing_address'];$sets=[];$args=[];foreach($cmap as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$b[$k];}if($sets){$args[]=$clientId;$db->prepare('UPDATE client_accounts SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute($args);}api_json(['client'=>st_client_account($db,$clientId)]);
        }
    }

    // ADMIN
    if(str_starts_with($route,'admin/')){
        $me=st_require_user($user,'ADMIN');$date=api_date();
        if($route==='admin/dashboard'&&$method==='GET'){
            $q=$db->prepare(st_job_select().' WHERE j.service_date=? ORDER BY j.id');$q->execute([$date]);$jobs=[];foreach(st_rows($q->fetchAll()) as $j)$jobs[]=st_sync_risk($db,$j);$k=['total'=>count($jobs),'completed'=>0,'cleaning'=>0,'assigned'=>0,'unassigned'=>0,'atRisk'=>0,'rescue'=>0];$ready=0;
            foreach($jobs as $j){if($j['status']==='COMPLETED')$k['completed']++;if(in_array($j['status'],['CLEANING','ARRIVED','EN_ROUTE'],true))$k['cleaning']++;if($j['assigned_cleaner_id']&&!in_array($j['status'],['COMPLETED','CANCELLED'],true))$k['assigned']++;if(!$j['assigned_cleaner_id']&&!in_array($j['status'],['COMPLETED','CANCELLED'],true))$k['unassigned']++;if(in_array($j['risk_level'],['ORANGE','RED'],true))$k['atRisk']++;if($j['status']==='RESCUE'||$j['rescue_state']==='ACTIVE')$k['rescue']++;if($j['status']==='COMPLETED'||(!empty($j['eta'])&&$j['eta']<='15:00'))$ready++;}usort($jobs,fn($a,$b)=>$b['risk_score']<=>$a['risk_score']);$pct=count($jobs)?round($ready/count($jobs)*100):100;$capacity=st_summarize_capacity(st_cleaner_rows($db,$date),$jobs,st_get_settings($db));api_json(['date'=>$date,'kpis'=>$k,'sla'=>['projectedReadyPct'=>$pct,'health'=>$pct>=98?'GREEN':($pct>=90?'ORANGE':'RED')],'capacity'=>$capacity,'jobs'=>$jobs]);
        }
        if($route==='admin/objects'&&$method==='GET'){$rows=st_rows($db->query("SELECT o.*,ca.company_name,cu.full_name client_name FROM objects o LEFT JOIN client_accounts ca ON ca.id=o.client_id LEFT JOIN users cu ON cu.id=ca.user_id ORDER BY CASE o.approval_status WHEN 'PENDING' THEN 0 ELSE 1 END,o.active DESC,o.code")->fetchAll());api_json(['objects'=>$rows]);}
        if($route==='admin/objects'&&$method==='POST'){
            $b=api_body();foreach(['code','name','address','zone'] as $k)if(empty($b[$k]))throw new STHttpException('code, name, address and zone are required',400);$clientId=(int)($b['clientId']??0);if($clientId&&!st_client_account($db,$clientId))throw new STHttpException('Client not found',404);$approval=in_array(($b['approvalStatus']??'APPROVED'),['PENDING','APPROVED','REJECTED'],true)?$b['approvalStatus']:'APPROVED';$active=array_key_exists('active',$b)?api_bool($b['active']):($approval==='APPROVED'?1:0);try{$q=$db->prepare("INSERT INTO objects(client_id,code,name,address,zone,lat,lng,apartment_type,bedrooms,bathrooms,duration_minutes,payout,client_price,checkout_time,deadline_time,access_instructions,key_instructions,parking,linen_location,supplies_location,wifi,notes,active,approval_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$q->execute([$clientId?:null,$b['code'],$b['name'],$b['address'],$b['zone'],$b['lat']??null,$b['lng']??null,$b['apartmentType']??'Apartment',(int)($b['bedrooms']??1),(int)($b['bathrooms']??1),(int)($b['durationMinutes']??60),(float)($b['payout']??20),(float)($b['clientPrice']??0),$b['checkoutTime']??'10:00',$b['deadlineTime']??'15:00',$b['accessInstructions']??'',$b['keyInstructions']??'',$b['parking']??'',$b['linenLocation']??'',$b['suppliesLocation']??'',$b['wifi']??'',$b['notes']??'',$active,$approval]);}catch(PDOException $e){if(($e->errorInfo[1]??0)===1062)throw new STHttpException('Object code already exists',409);throw $e;}$id=(int)$db->lastInsertId();st_insert_default_checklist($db,$id);$q=$db->prepare('SELECT * FROM objects WHERE id=?');$q->execute([$id]);api_json(['object'=>st_normalize_row($q->fetch())],201);
        }
        if(preg_match('#^admin/objects/(\d+)/checklist$#',$route,$m)&&$method==='PUT'){
            $oid=(int)$m[1];$b=api_body();$q=$db->prepare('SELECT id FROM objects WHERE id=?');$q->execute([$oid]);if(!$q->fetch())throw new STHttpException('Object not found',404);if(empty($b['items'])||!is_array($b['items']))throw new STHttpException('At least one checklist item is required',400);
            st_transaction($db,function()use($db,$oid,$b){$db->prepare('DELETE FROM checklist_items WHERE object_id=?')->execute([$oid]);$i=$db->prepare('INSERT INTO checklist_items(object_id,label,required,photo_required,photo_category,sort_order) VALUES(?,?,?,?,?,?)');foreach($b['items'] as $n=>$x){$label=trim((string)($x['label']??''));if(!$label)throw new STHttpException('Checklist label is required',400);$i->execute([$oid,$label,($x['required']??true)===false?0:1,st_bool($x['photoRequired']??false)?1:0,$x['photoCategory']??null,$n+1]);}});$q=$db->prepare('SELECT * FROM checklist_items WHERE object_id=? ORDER BY sort_order,id');$q->execute([$oid]);api_json(['checklist'=>st_rows($q->fetchAll())]);
        }
        if(preg_match('#^admin/objects/(\d+)$#',$route,$m)){
            $id=(int)$m[1];if($method==='GET'){$q=$db->prepare("SELECT o.*,ca.company_name,cu.full_name client_name,cu.email client_email FROM objects o LEFT JOIN client_accounts ca ON ca.id=o.client_id LEFT JOIN users cu ON cu.id=ca.user_id WHERE o.id=?");$q->execute([$id]);$o=$q->fetch();if(!$o)throw new STHttpException('Object not found',404);$q=$db->prepare('SELECT * FROM checklist_items WHERE object_id=? ORDER BY sort_order,id');$q->execute([$id]);$check=st_rows($q->fetchAll());$q=$db->prepare(st_job_select().' WHERE j.object_id=? ORDER BY j.service_date DESC LIMIT 100');$q->execute([$id]);api_json(['object'=>st_normalize_row($o),'checklist'=>$check,'history'=>st_rows($q->fetchAll())]);}
            if($method==='PATCH'){
                $b=api_body();$q=$db->prepare('SELECT o.*,ca.user_id client_user_id FROM objects o LEFT JOIN client_accounts ca ON ca.id=o.client_id WHERE o.id=?');$q->execute([$id]);$before=$q->fetch();if(!$before)throw new STHttpException('Object not found',404);
                $map=['clientId'=>'client_id','code'=>'code','name'=>'name','address'=>'address','zone'=>'zone','lat'=>'lat','lng'=>'lng','apartmentType'=>'apartment_type','bedrooms'=>'bedrooms','bathrooms'=>'bathrooms','durationMinutes'=>'duration_minutes','payout'=>'payout','clientPrice'=>'client_price','checkoutTime'=>'checkout_time','deadlineTime'=>'deadline_time','accessInstructions'=>'access_instructions','keyInstructions'=>'key_instructions','parking'=>'parking','linenLocation'=>'linen_location','suppliesLocation'=>'supplies_location','wifi'=>'wifi','notes'=>'notes','active'=>'active','approvalStatus'=>'approval_status'];
                $sets=[];$args=[];foreach($map as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$k==='active'?api_bool($b[$k]):$b[$k];}
                if($sets){$args[]=$id;$q=$db->prepare('UPDATE objects SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=?');$q->execute($args);}
                $q=$db->prepare('SELECT o.*,ca.user_id client_user_id FROM objects o LEFT JOIN client_accounts ca ON ca.id=o.client_id WHERE o.id=?');$q->execute([$id]);$o=$q->fetch();if(!$o)throw new STHttpException('Object not found',404);
                if(($before['approval_status']??null)!==($o['approval_status']??null) && !empty($o['client_user_id'])){if($o['approval_status']==='APPROVED')st_notify($db,(int)$o['client_user_id'],'OBJECT_APPROVED','Property approved',$o['code'].' · '.$o['name'].' is ready for booking.');elseif($o['approval_status']==='REJECTED')st_notify($db,(int)$o['client_user_id'],'OBJECT_REJECTED','Property needs review',$o['code'].' · '.$o['name'].' was not approved. Contact Operations.');}
                api_json(['object'=>st_normalize_row($o)]);
            }
        }
        if($route==='admin/jobs'&&$method==='GET'){$status=$_GET['status']??null;$cleaner=$_GET['cleanerId']??null;$sql=st_job_select().' WHERE j.service_date=?';$args=[$date];if($status){$sql.=' AND j.status=?';$args[]=$status;}if($cleaner){$sql.=' AND j.assigned_cleaner_id=?';$args[]=(int)$cleaner;}$sql.=' ORDER BY j.planned_start,j.id';$q=$db->prepare($sql);$q->execute($args);$jobs=array_map('st_decorate_job_risk',st_rows($q->fetchAll()));api_json(['jobs'=>$jobs]);}
        if($route==='admin/jobs'&&$method==='POST'){$b=api_body();if(empty($b['objectId'])||empty($b['serviceDate']))throw new STHttpException('objectId and serviceDate required',400);$b['createdByUserId']=$me['id'];$b['bookingSource']=$b['bookingSource']??'ADMIN';$job=st_create_job_from_object($db,(int)$b['objectId'],(string)$b['serviceDate'],$b);st_add_event($db,$job['id'],$me['id'],'JOB_CREATED',['serviceDate'=>$b['serviceDate']]);api_json(['job'=>st_get_job($db,$job['id'])],201);}
        if($route==='admin/jobs/generate'&&$method==='POST'){$b=api_body();if(empty($b['serviceDate']))throw new STHttpException('serviceDate required',400);$ids=$b['objectIds']??[];if(!$ids){$ids=array_column($db->query('SELECT id FROM objects WHERE active=1')->fetchAll(),'id');}$created=[];$skipped=[];foreach($ids as $oid){try{$j=st_create_job_from_object($db,(int)$oid,(string)$b['serviceDate'],['marketplaceVisible'=>($b['publish']??true)!==false,'createdByUserId'=>$me['id'],'bookingSource'=>'ADMIN']);$created[]=$j;st_add_event($db,$j['id'],$me['id'],'JOB_GENERATED',['serviceDate'=>$b['serviceDate']]);}catch(STHttpException $e){if($e->status===409)$skipped[]=(int)$oid;else throw $e;}}api_json(['created'=>count($created),'skipped'=>$skipped,'jobIds'=>array_column($created,'id')],201);}
        if(preg_match('#^admin/jobs/(\d+)$#',$route,$m)){
            $id=(int)$m[1];if($method==='GET'){$detail=st_full_job($db,$id,true);if(!$detail)throw new STHttpException('Job not found',404);api_json($detail);}if($method==='PATCH'){$b=api_body();$map=['plannedStart'=>'planned_start','deadline'=>'deadline','durationMinutes'=>'duration_minutes','payout'=>'payout','clientPrice'=>'client_price','bonus'=>'bonus','extraRevenue'=>'extra_revenue','extraCost'=>'extra_cost','financialStatus'=>'financial_status','marketplaceVisible'=>'marketplace_visible','status'=>'status'];$sets=[];$args=[];foreach($map as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$k==='marketplaceVisible'?api_bool($b[$k]):$b[$k];}if($sets){$args[]=$id;$q=$db->prepare('UPDATE cleaning_jobs SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=?');$q->execute($args);st_add_event($db,$id,$me['id'],'JOB_UPDATED',$b);}api_json(['job'=>st_get_job($db,$id)]);}
        }
        if(preg_match('#^admin/jobs/(\d+)/assign$#',$route,$m)&&$method==='POST'){$id=(int)$m[1];$b=api_body();$job=st_get_job($db,$id);if(!$job)throw new STHttpException('Job not found',404);$cid=(int)($b['cleanerId']??0);$q=$db->prepare('SELECT * FROM cleaners WHERE id=? AND active=1');$q->execute([$cid]);if(!$q->fetch())throw new STHttpException('Cleaner not found',404);$oldCid=(int)($job['assigned_cleaner_id']??0);$db->prepare("UPDATE cleaning_jobs SET assigned_cleaner_id=?,status='ACCEPTED',accepted_at=?,marketplace_visible=0,rescue_state='NONE',updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$cid,st_now(),$id]);if($oldCid&&$oldCid!==$cid)st_update_job_plan_for_cleaner($db,$oldCid,$job['service_date']);st_update_job_plan_for_cleaner($db,$cid,$job['service_date']);st_add_event($db,$id,$me['id'],'ADMIN_ASSIGNED',['cleanerId'=>$cid]);$q=$db->prepare('SELECT user_id FROM cleaners WHERE id=?');$q->execute([$cid]);st_notify($db,(int)$q->fetchColumn(),'ASSIGNED','New job assigned',$job['object_code'].' was assigned by operations');api_json(['job'=>st_get_job($db,$id)]);}
        if(preg_match('#^admin/jobs/(\d+)/rescue$#',$route,$m)&&$method==='POST'){$id=(int)$m[1];$b=api_body();$job=st_get_job($db,$id);if(!$job)throw new STHttpException('Job not found',404);$bonus=(float)($b['bonus']??max((float)$job['bonus'],6));$cid=(int)($b['cleanerId']??0);if($cid){$q=$db->prepare('SELECT * FROM cleaners WHERE id=? AND active=1');$q->execute([$cid]);if(!$q->fetch())throw new STHttpException('Cleaner not found',404);$oldCid=(int)($job['assigned_cleaner_id']??0);$db->prepare("UPDATE cleaning_jobs SET assigned_cleaner_id=?,status='ACCEPTED',bonus=?,marketplace_visible=0,rescue_state='ASSIGNED',accepted_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$cid,$bonus,st_now(),$id]);if($oldCid&&$oldCid!==$cid)st_update_job_plan_for_cleaner($db,$oldCid,$job['service_date']);st_update_job_plan_for_cleaner($db,$cid,$job['service_date']);$q=$db->prepare('SELECT user_id FROM cleaners WHERE id=?');$q->execute([$cid]);st_notify($db,(int)$q->fetchColumn(),'RESCUE','Rescue assignment',$job['object_code'].' rescue +€'.$bonus);st_add_event($db,$id,$me['id'],'RESCUE_ASSIGNED',['cleanerId'=>$cid,'bonus'=>$bonus]);}else{$db->prepare("UPDATE cleaning_jobs SET status='RESCUE',bonus=?,marketplace_visible=1,rescue_state='ACTIVE',updated_at=CURRENT_TIMESTAMP WHERE id=?")->execute([$bonus,$id]);st_add_event($db,$id,$me['id'],'RESCUE_OPENED',['bonus'=>$bonus]);}api_json(['job'=>st_get_job($db,$id)]);}
        if(preg_match('#^admin/jobs/(\d+)/bonus$#',$route,$m)&&$method==='POST'){$id=(int)$m[1];$b=api_body();if(!st_get_job($db,$id))throw new STHttpException('Job not found',404);$bonus=(float)($b['bonus']??0);$db->prepare('UPDATE cleaning_jobs SET bonus=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$bonus,$id]);st_add_event($db,$id,$me['id'],'BONUS_UPDATED',['bonus'=>$bonus]);api_json(['job'=>st_get_job($db,$id)]);}
        if($route==='admin/cleaners'&&$method==='GET'){$q=$db->query("SELECT c.*,u.full_name,u.email,u.phone,u.language,u.active user_active FROM cleaners c JOIN users u ON u.id=c.user_id ORDER BY c.active DESC,c.reliability_score DESC");$rows=st_rows($q->fetchAll());foreach($rows as &$c){$c['preferred_zones']=st_json_decode($c['preferred_zones']??'[]',[]);$q=$db->prepare("SELECT COUNT(*) FROM cleaning_jobs WHERE assigned_cleaner_id=? AND service_date=? AND status!='CANCELLED'");$q->execute([$c['id'],$date]);$c['today_jobs']=(int)$q->fetchColumn();$q=$db->prepare("SELECT COALESCE(SUM(payout+bonus),0) FROM cleaning_jobs WHERE assigned_cleaner_id=? AND service_date=? AND status='COMPLETED'");$q->execute([$c['id'],$date]);$c['today_earnings']=(float)$q->fetchColumn();}unset($c);api_json(['cleaners'=>$rows]);}
        if($route==='admin/cleaners'&&$method==='POST')api_json(st_create_cleaner_account($db,api_body()),201);
        if(preg_match('#^admin/cleaners/(\d+)$#',$route,$m)&&$method==='PATCH'){$id=(int)$m[1];$b=api_body();$q=$db->prepare('SELECT * FROM cleaners WHERE id=?');$q->execute([$id]);$c=$q->fetch();if(!$c)throw new STHttpException('Cleaner not found',404);$map=['mode'=>'mode','reliabilityScore'=>'reliability_score','rating'=>'rating','transport'=>'transport','preferredZones'=>'preferred_zones','maxJobsDay'=>'max_jobs_day','active'=>'active'];$sets=[];$args=[];foreach($map as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$v=$b[$k];if($k==='preferredZones')$v=st_json($v??[]);if($k==='active')$v=api_bool($v);$args[]=$v;}if($sets){$args[]=$id;$db->prepare('UPDATE cleaners SET '.implode(',',$sets).' WHERE id=?')->execute($args);}if(array_key_exists('fullName',$b)||array_key_exists('phone',$b)||array_key_exists('email',$b)||array_key_exists('language',$b)){$q=$db->prepare('SELECT user_id FROM cleaners WHERE id=?');$q->execute([$id]);$uid=(int)$q->fetchColumn();$umap=['fullName'=>'full_name','phone'=>'phone','email'=>'email','language'=>'language'];$sets=[];$args=[];foreach($umap as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$args[]=$k==='language'?st_valid_locale((string)$b[$k]):$b[$k];}if($sets){$args[]=$uid;$db->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=?')->execute($args);}}$q=$db->prepare('SELECT c.*,u.full_name,u.email,u.phone,u.language FROM cleaners c JOIN users u ON u.id=c.user_id WHERE c.id=?');$q->execute([$id]);$r=st_normalize_row($q->fetch());$r['preferred_zones']=st_json_decode($r['preferred_zones']??'[]',[]);api_json(['cleaner'=>$r]);}
        if(preg_match('#^admin/cleaners/(\d+)/password$#',$route,$m)&&$method==='POST'){$id=(int)$m[1];$b=api_body();$password=(string)($b['password']??'');if(strlen($password)<10)throw new STHttpException('Temporary password must be at least 10 characters',400);$q=$db->prepare('SELECT user_id FROM cleaners WHERE id=?');$q->execute([$id]);$uid=(int)$q->fetchColumn();if(!$uid)throw new STHttpException('Cleaner not found',404);$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$uid]);st_notify($db,$uid,'SECURITY','Password reset','Operations reset your login password. Change it in Profile after signing in.');api_json(['ok'=>true]);}
        if($route==='admin/clients'&&$method==='GET'){
            $month=st_month_bounds((string)($_GET['month']??date('Y-m')));$q=$db->query("SELECT ca.*,u.full_name,u.email,u.phone,u.language,u.active user_active FROM client_accounts ca JOIN users u ON u.id=ca.user_id ORDER BY u.active DESC,COALESCE(ca.company_name,u.full_name)");$rows=st_rows($q->fetchAll());foreach($rows as &$c){$q=$db->prepare('SELECT COUNT(*) total,SUM(approval_status=\'APPROVED\') approved FROM objects WHERE client_id=?');$q->execute([$c['id']]);$os=$q->fetch();$c['objects']=(int)($os['total']??0);$c['approved_objects']=(int)($os['approved']??0);$q=$db->prepare("SELECT COUNT(*) jobs,COALESCE(SUM(client_price+extra_revenue),0) revenue FROM cleaning_jobs WHERE client_id=? AND service_date BETWEEN ? AND ? AND status='COMPLETED'");$q->execute([$c['id'],$month['from'],$month['to']]);$fs=$q->fetch();$c['month_jobs']=(int)($fs['jobs']??0);$c['month_revenue']=(float)($fs['revenue']??0);}unset($c);api_json(['clients'=>$rows,'month'=>$month['month']]);
        }
        if($route==='admin/clients'&&$method==='POST')api_json(st_create_client_account($db,api_body()),201);
        if(preg_match('#^admin/clients/(\d+)$#',$route,$m)&&$method==='PATCH'){
            $id=(int)$m[1];$client=st_client_account($db,$id);if(!$client)throw new STHttpException('Client not found',404);$b=api_body();$cmap=['accountType'=>'account_type','companyName'=>'company_name','billingName'=>'billing_name','ico'=>'ico','dic'=>'dic','icDph'=>'ic_dph','billingAddress'=>'billing_address','notes'=>'notes'];$sets=[];$args=[];foreach($cmap as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$v=$b[$k];if($k==='accountType')$v=$v==='MANAGER'?'MANAGER':'OWNER';$args[]=$v;}if($sets){$args[]=$id;$db->prepare('UPDATE client_accounts SET '.implode(',',$sets).',updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute($args);}$uid=(int)$client['user_id'];$umap=['fullName'=>'full_name','phone'=>'phone','email'=>'email','language'=>'language','active'=>'active'];$sets=[];$args=[];foreach($umap as $k=>$col)if(array_key_exists($k,$b)){$sets[]="$col=?";$v=$b[$k];if($k==='language')$v=st_valid_locale((string)$v);if($k==='active')$v=api_bool($v);$args[]=$v;}if(array_key_exists('accountType',$b)){$sets[]='role=?';$args[]=$b['accountType']==='MANAGER'?'MANAGER':'OWNER';}if($sets){$args[]=$uid;$db->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=?')->execute($args);}api_json(['client'=>st_client_account($db,$id)]);
        }
        if(preg_match('#^admin/clients/(\d+)/password$#',$route,$m)&&$method==='POST'){
            $id=(int)$m[1];$b=api_body();$password=(string)($b['password']??'');if(strlen($password)<10)throw new STHttpException('Temporary password must be at least 10 characters',400);$client=st_client_account($db,$id);if(!$client)throw new STHttpException('Client not found',404);$db->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),(int)$client['user_id']]);st_notify($db,(int)$client['user_id'],'SECURITY','Password reset','Operations reset your login password.');api_json(['ok'=>true]);
        }
        if($route==='admin/finance'&&$method==='GET')api_json(st_admin_finance_report($db,(string)($_GET['month']??date('Y-m'))));
        if($route==='admin/finance/entries'&&$method==='POST'){
            $b=api_body();$date=(string)($b['entryDate']??st_today());$type=(string)($b['entryType']??'');$amount=(float)($b['amount']??0);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!in_array($type,['INCOME','EXPENSE'],true)||$amount<=0)throw new STHttpException('Valid date, type and positive amount are required',400);$q=$db->prepare('INSERT INTO financial_entries(entry_date,entry_type,category,amount,description,client_id,object_id,job_id,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$date,$type,trim((string)($b['category']??'OTHER'))?:'OTHER',$amount,trim((string)($b['description']??''))?:null,($b['clientId']??null)?:null,($b['objectId']??null)?:null,($b['jobId']??null)?:null,$me['id']]);$id=(int)$db->lastInsertId();$q=$db->prepare('SELECT * FROM financial_entries WHERE id=?');$q->execute([$id]);api_json(['entry'=>st_normalize_row($q->fetch())],201);
        }
        if(preg_match('#^admin/finance/entries/(\d+)$#',$route,$m)&&$method==='DELETE'){$id=(int)$m[1];$q=$db->prepare('DELETE FROM financial_entries WHERE id=?');$q->execute([$id]);if($q->rowCount()!==1)throw new STHttpException('Finance entry not found',404);api_json(['ok'=>true]);}
        if($route==='admin/issues'&&$method==='GET'){$q=$db->query("SELECT i.*,j.service_date,j.status job_status,o.code object_code,o.address,u.full_name cleaner_name FROM issues i JOIN cleaning_jobs j ON j.id=i.job_id JOIN objects o ON o.id=j.object_id LEFT JOIN cleaners c ON c.id=i.cleaner_id LEFT JOIN users u ON u.id=c.user_id ORDER BY CASE i.status WHEN 'OPEN' THEN 0 ELSE 1 END, CASE i.priority WHEN 'HIGH' THEN 0 ELSE 1 END, i.id DESC");$rows=st_rows($q->fetchAll());foreach($rows as &$i)$i['photos']=st_json_decode($i['photos_json']??'[]',[]);unset($i);api_json(['issues'=>$rows]);}
        if(preg_match('#^admin/issues/(\d+)$#',$route,$m)&&$method==='PATCH'){$id=(int)$m[1];$b=api_body();$q=$db->prepare('SELECT * FROM issues WHERE id=?');$q->execute([$id]);$issue=$q->fetch();if(!$issue)throw new STHttpException('Issue not found',404);$status=(string)($b['status']??$issue['status']);$resolved=$status==='RESOLVED';$q=$db->prepare('UPDATE issues SET status=?,resolution_note=?,resolved_at=? WHERE id=?');$q->execute([$status,$b['resolutionNote']??$issue['resolution_note'],$resolved?st_now():null,$id]);if($resolved){$q=$db->prepare("SELECT COUNT(*) FROM issues WHERE job_id=? AND status='OPEN'");$q->execute([$issue['job_id']]);if((int)$q->fetchColumn()===0)$db->prepare('UPDATE cleaning_jobs SET issue_flag=0 WHERE id=?')->execute([$issue['job_id']]);}st_add_event($db,(int)$issue['job_id'],$me['id'],'ISSUE_UPDATED',['issueId'=>$id,'status'=>$status]);$q=$db->prepare('SELECT * FROM issues WHERE id=?');$q->execute([$id]);api_json(['issue'=>st_normalize_row($q->fetch())]);}
        if($route==='admin/capacity'&&$method==='GET'){$q=$db->prepare(st_job_select()." WHERE j.service_date=? AND j.status!='CANCELLED'");$q->execute([$date]);$jobs=st_rows($q->fetchAll());api_json(['date'=>$date,'capacity'=>st_summarize_capacity(st_cleaner_rows($db,$date),$jobs,st_get_settings($db)),'cleaners'=>st_cleaner_rows($db,$date),'jobs'=>$jobs]);}
        if($route==='admin/analytics'&&$method==='GET'){$from=(string)($_GET['from']??'2000-01-01');$to=(string)($_GET['to']??'2099-12-31');$q=$db->prepare(st_job_select().' WHERE j.service_date BETWEEN ? AND ? ORDER BY j.service_date');$q->execute([$from,$to]);$rows=st_rows($q->fetchAll());$completed=array_values(array_filter($rows,fn($j)=>$j['status']==='COMPLETED'));$onTime=array_values(array_filter($completed,fn($j)=>!empty($j['completed_at'])&&substr($j['completed_at'],11,5)<='15:00'));$by=[];$rescue=0;$cancelled=0;foreach($rows as $j){$d=$j['service_date'];$by[$d]??=['date'=>$d,'total'=>0,'completed'=>0,'rescue'=>0,'cancelled'=>0];$by[$d]['total']++;if($j['status']==='COMPLETED')$by[$d]['completed']++;if(!empty($j['rescue_state'])&&$j['rescue_state']!=='NONE'){$by[$d]['rescue']++;$rescue++;}if($j['status']==='CANCELLED'){$by[$d]['cancelled']++;$cancelled++;}}$q=$db->prepare('SELECT COUNT(*) FROM issues WHERE created_at>=? AND created_at<=?');$q->execute([$from.' 00:00:00',$to.' 23:59:59']);$issues=(int)$q->fetchColumn();$ranking=st_rows($db->query('SELECT c.id,u.full_name,c.reliability_score,c.rating,c.completed_jobs,c.reclean_rate,c.cancellation_rate,c.avg_delay_minutes FROM cleaners c JOIN users u ON u.id=c.user_id ORDER BY c.reliability_score DESC')->fetchAll());$objects=st_rows($db->query('SELECT o.id,o.code,o.name,o.duration_minutes,COUNT(j.id) jobs,ROUND(AVG(j.duration_minutes),1) avg_duration FROM objects o LEFT JOIN cleaning_jobs j ON j.object_id=o.id GROUP BY o.id ORDER BY jobs DESC')->fetchAll());api_json(['summary'=>['jobs'=>count($rows),'completed'=>count($completed),'onTimePct'=>count($completed)?round(count($onTime)/count($completed)*100,1):100,'rescue'=>$rescue,'cancelled'=>$cancelled,'issues'=>$issues],'byDate'=>array_values($by),'cleanerRanking'=>$ranking,'objectPerformance'=>$objects]);}
        if($route==='admin/settings'&&$method==='GET')api_json(['settings'=>st_get_settings($db)]);
        if($route==='admin/settings'&&$method==='PATCH'){$b=api_body();foreach($b as $k=>$v)st_set_setting($db,(string)$k,$v);api_json(['settings'=>st_get_settings($db)]);}
    }

    throw new STHttpException('API route not found',404);
} catch(STHttpException $e){api_json(['error'=>$e->getMessage(),...$e->extra],$e->status);} catch(PDOException $e){error_log('Shine Time DB error: '.$e->getMessage());api_json(['error'=>'Database error. Check server logs.'],500);} catch(Throwable $e){error_log('Shine Time error: '.$e->getMessage());api_json(['error'=>'Unexpected server error'],500);}
